tag:
	gcc tag.c libdw1000.c libdw1000Spi.c runTag.c -o tag -lpigpio -lm -lrt -lpthread -lwiringPi
anchor:
	gcc anchor.c libdw1000.c libdw1000Spi.c runAnchor.c -o anchor -lpigpio -lm -lrt -lpthread -lwiringPi
clean:
	rm tag anchor
